### ISSUE TITLE
fields with annotations lead to "no arguments allowed for nullary constructor"

### ISSUE THREAD

**Issue by yanns** [propensive/magnolia#103]
I am trying to use magnolia for the sphere-json and sphere-mongo libs.
We provide annotations on case class fields.
Ex:
```
  case class AnotherThing(
    @MongoKey("first_name") firstName: String
  )
```

By doing that, I see the following error:
```
no arguments allowed for nullary constructor MongoKey: ()io.sphere.mongo.generic.annotations.MongoKey
[error] Note that 'value' is not a parameter name of the invoked method.
[error]       val testFormat: MongoFormat[AnotherThing] = MongoFormatDerivation.gen
```

https://github.com/sphereio/sphere-scala-libs/blob/try_magnolia/mongo/src/test/scala/io/sphere/mongo/Serialization2Test.scala#L56

Any idea/hint how I could solve that? Or is it a limitation from magnolia?

**Comment by propensive** [comment]
Hmm. It looks like some strange interaction between Magnolia and the annotation... Could you link me to the source for the derivation object?

**Comment by yanns** [comment]
Thx for the quick feedback!

The derivation object is here: https://github.com/sphereio/sphere-scala-libs/blob/try_magnolia/mongo/src/main/scala/io/sphere/mongo/magnolia/MongoFormatDerivation.scala
(please take in consideration that it's WIP and my first goal is to check whether we can use magnolia or not instead of macros + sbt plugin)

**Comment by yanns** [comment]
I tried again with the 0.10.0 version, and the issue is still present.
I'd glab to help if you give me any pointers.

**Comment by kubukoz** [comment]
Just got the same error if the class itself is annotated with something that takes arguments (in this case, swagger-annotations' `ApiModel`). I'm using a copy of https://github.com/etaty/scalacheck-magnolia/blob/master/src/main/scala/scalacheckmagnolia/MagnoliaArbitrary.scala and magnolia 0.10.0.

**Comment by yanns** [comment]
This error is still happening when I use a scala type alias for the java annotation.
Ex of a compilation error:
https://github.com/sphereio/sphere-scala-libs/blob/try_magnolia/mongo/src/test/scala/io/sphere/mongo/generic/DeriveMongoformat2Spec.scala#L109

The error is coming from:
```
  @MongoTypeHint("bar")
  case class Custom(width: Int, height: Int) extends PictureSize
```
`MongoTypeHint` is a scala type alias for a java annotation:
```
type MongoTypeHint = io.sphere.mongo.generic.annotations.MongoTypeHint
```

The java annotation:
```
@Retention(RetentionPolicy.RUNTIME)
@Target({TYPE})
public @interface MongoTypeHint {
    String value() default "";
}
```

**Comment by yanns** [comment]
Update: I was still using the `0.10` version.
In the `0.11` version, I don't have this issue anymore.
