### ISSUE TITLE
Magnolia fails to dispatch through some recursive ADTs 

### ISSUE THREAD

**Issue by vpavkin** [propensive/magnolia#111]
Originally reported by @scalway on [gitter](https://gitter.im/propensive/magnolia?at=5b2e40b2b9c2fb2557050890).

Magnolia fails to dispatch on the following recursive ADT (tested using circe-magnolia):

```scala
sealed trait Msg {}

case class Hello(text:String) extends Msg
case class ByeBye(text:String) extends Msg
case class Multi(msgs:Seq[Msg]) extends Msg

import io.circe.magnolia.derivation.encoder.semiauto._

// fails with
// magnolia: could not find Encoder.Typeclass for type Seq[Playground.this.Msg]
// in parameter 'msgs' of product type Playground.this.Multi
// in coproduct type Playground.this.Msg
val encoder = deriveMagnoliaEncoder[Msg]
```

This happens when magnolia macro **is not implicit**. In case of implicit macro (auto mode) everything is fine.

See deriver implementation [here] (https://github.com/circe/circe-magnolia/blob/master/derivation/src/main/scala/io/circe/magnolia/MagnoliaEncoder.scala).

**Comment by vpavkin** [comment]
Scastie worksheet: https://scastie.scala-lang.org/vpavkin/lTr16ttTRsygkSNGLPYK3A

**Comment by joroKr21** [comment]
This works for me (it's also what I would expect if the macro is not implicit):
```scala
implicit lazy val encoder: Encoder[Msg] = deriveMagnoliaEncoder[Msg]
implicit lazy val decoder: Decoder[Msg] = deriveMagnoliaDecoder[Msg]
```

**Comment by vpavkin** [comment]
Confirm, worked for me. Thanks @joroKr21 !
