### ISSUE TITLE
Update version to 0.8.0 on magnolia.work

### ISSUE THREAD

**Issue by vpavkin** [propensive/magnolia#113]
Couldn't find where to send the PR, since the https://github.com/propensive/magnolia-website seems to be out of sync with the web page.

Anyway, people are reporting 0.7.1 bugs that were fixed. Let's save them some time and update the version :)

**Comment by mikla** [comment]
Update it to `0.9.0` :)

**Comment by ArturGajowy** [comment]
To 0.9.1 even!

**Comment by lemastero** [comment]
Couldn't agree more, yet this one goes to .11 and more.
Anything other than [![Latest version](https://index.scala-lang.org/propensive/magnolia/latest.svg)](https://index.scala-lang.org/propensive/magnolia) would be inconceivable!
