### ISSUE TITLE
Support multi typeclass which refers to each other

### ISSUE THREAD

**Issue by jilen** [propensive/magnolia#115]
For two typeclass which involes between each other, there seems no way to define derivation rule.

With shapeless I would probably define something like this. 
```scala
import shapeless._
import shapeless.labelled._

trait FieldEncoder[A] {
  def encode(fn: String, a: A): Unit
}

trait ObjectEncoder[A] {
  def encode(a: A): Unit
}

implicit def hlistEncoder[K <: Symbol, H , L <: HList ](
  implicit  key: Witness.Aux[K],
   hE: Lazy[FieldEncoder[H]],
  lE: Lazy[ObjectEncoder[L]]
): ObjectEncoder[FieldType[K, H] :: L] = ???


implicit def objFieldEncoder[A](
  implicit fe: ObjectEncoder[A]
): FieldEncoder[A] = new FieldEncoder[A] {
  def encode(fn: String, a: A) = {
    println(fn)
    fe.encode(a)
  }
}
```

**Comment by fommil** [comment]
I'm not sure I would consider this to be typeclass derivation, in the strictest sense. It is really a generic program.

**Comment by jilen** [comment]
@fommil Sounds reasonable. And I found it could be modeled as a single typeclass sometime

**Comment by fommil** [comment]
@jilen I know the problem you're trying to solve though, it comes up in JSON encoding / decoding. I prefer to allow such cases and have an encoding for them: e.g. by wrapping with an `xvalue` field. See https://gitlab.com/fommil/scalaz-deriving/blob/master/examples/jsonformat/src/main/scala/jsonformat/JsMagnolia.scala

**Comment by jilen** [comment]
@fommil Thanks for sharing.
