### ISSUE TITLE
shouldBeLazy is not working as expected

### ISSUE THREAD

**Issue by fommil** [propensive/magnolia#122]
@joroKr21 I've had to back this out in my local fork

```diff
modified   core/shared/src/main/scala/magnolia.scala
@@ -147,13 +147,7 @@ object Magnolia {
     }
 
     def deferredVal(name: TermName, tpe: Type, rhs: Tree): Tree = {
-      val shouldBeLazy = rhs.exists {
-        case q"$magnolia.Deferred.apply[$_]($_)" => magnolia.symbol == magnoliaPkg
-        case tree => enclosingVals.contains(tree.symbol)
-      }
-
-      if (shouldBeLazy) q"lazy val $name: $tpe = $rhs"
-      else q"val $name = $rhs"
+      q"lazy val $name: $tpe = $rhs"
     }
```

so that my json encoder/decoder works in https://gitlab.com/fommil/scalaz-deriving/tree/upgrade-magnolia otherwise I get `NullPointerException`s... I don't have a minimisation of the problem but there is definitely a test needed here. As a workaround I'd be fine with semiauto always being lazy.

**Comment by joroKr21** [comment]
That's entirely possible. This check is a bit finicky and I don't like it either but it was the best I could come up with to mitigate #95. It would be nice to get a reproduction and see what kind of code is tripping the check.

**Comment by joroKr21** [comment]
@fommil could it be that `enclosingVals` doesn't work properly because the trees are not typed yet (macro annotations and all)?
