### ISSUE TITLE
inst$macro$114  is already defined as value inst$macro$114

### ISSUE THREAD

**Issue by ryan-williams** [propensive/magnolia#142]
In 2.11.12, I'm seeing this compile error at calls to the `Magnolia.gen` macro, where deriving the instance requires some other implicit evidence instances to be materialized (which themselves may call some shapeless macros?)

I don't have an easy/minimal repro atm but wanted to mention in case it's clear what the problem / possible fix might be (e.g. is this a hard-coded instance-name string that is colliding with other macro-generated instances from shapeless?)

**Comment by ryan-williams** [comment]
[Here's a small repro](https://github.com/ryan-williams/scala-bugs/blob/c249b545d29564c30a5a05d30f85fc352ce4d062/src/main/scala/Test.scala):

```scala
import magnolia._
import org.hammerlab.test.Cmp

import scala.language.experimental.macros

trait TC[T]
object TC {
  type Typeclass[T] = TC[T]
  def  combine[T](ctx:   CaseClass[TC, T]): TC[T] = ???
  def dispatch[T](ctx: SealedTrait[TC, T]): TC[T] = ???
  implicit def gen[T]: TC[T] = macro Magnolia.gen[T]
}

case class A(value: Int)
case class B(ints: Array[A])

object Test {
  implicit def array[T](implicit cmp: Cmp[T]): TC[Array[T]] = ???
  TC.gen[B]  // 🚫: inst$macro$6  is already defined as value inst$macro$6
}
```

The problem occurs while [searching for](https://github.com/ryan-williams/scala-bugs/blob/c249b545d29564c30a5a05d30f85fc352ce4d062/src/main/scala/Test.scala#L18) an instance of [`Cmp`](https://github.com/hammerlab/test-utils/blob/v1.0.3/suite/shared/src/main/scala/org/hammerlab/cmp/CanEq.scala#L183), which has [a bunch of complicated shapeless-based derivations](https://github.com/hammerlab/test-utils/blob/v1.0.3/suite/shared/src/main/scala/org/hammerlab/cmp/CanEq.scala#L180).

It would be interesting to whittle down the `Cmp` derivations to pinpoint the interactions more specifically, but again, I'm also hoping that the nature of the error might suggest a fix without resorting to that!

**Comment by joroKr21** [comment]
You should be able to use @debug to print the generated tree. That might help identify the problem.

**Comment by joroKr21** [comment]
Magnolia doesn't work on Scala 2.11 because of how lazy vals are ecnoded :/
