### ISSUE TITLE
Cutting a new release?

### ISSUE THREAD

**Issue by nevillelyh** [propensive/magnolia#143]
Right now the scala-lang badge in README points to `0.10.1-jto` which is monkey-patched by @jto.
https://index.scala-lang.org/propensive/magnolia/magnolia/0.10.1-jto?target=_2.12

Is it possible to cut a new release so we can stop using this workaround?

**Comment by propensive** [comment]
Sorry this is taking so long - I've been really short of time. I'll try to speak to @jto today and see if I can grant him some rights to help publish the release (or prepare everything apart from pressing the final button). We're both in the same place right now, so hopefully an opportunity will arise!

**Comment by RafalSumislawski** [comment]
Hi @propensive @jto.
There was no release since a long time, and I'm waiting impatiently to use the new #152 feature in my [swaggerify](https://github.com/RafalSumislawski/swaggerify). Is there anything that I could help with? Some blocking issues?

**Comment by sirthias** [comment]
Yes. Unfortunately magnolia appears to be falling behind on multiple fronts, so that depending on it (as I currently do in [BORER](https://github.com/sirthias/borer/) starts becoming a liability.

@propensive Would you maybe like to declare "maintainer bankruptcy" and hand over stewardship to someone else completely? It'd be a shame, if magnolia simply withered away...

**Comment by adamw** [comment]
I've needed @RafalSumislawski 's feature in tapir as well (thanks Rafał! I think I need it in fact for the same purpose :) ), so I've published master as `"com.softwaremill" %% "magnolia" % "0.11.0-sml"`, but only for scala 2.12 (http://repo1.maven.org/maven2/com/softwaremill/magnolia_2.12/0.11.0-sml/). 

Hope you don't mind!

**Comment by adamw** [comment]
btw. important note - as `TypeName` has changed (it now has an additional constructor parameter), e.g. `circe-magnolia-derivation` no longer works - it would require a re-build & re-publish

**Comment by sirthias** [comment]
My current plan is to, for now, internalize a (patched) copy of Magnolia in [BORER](https://github.com/sirthias/borer/), so I can fix a few issues and also cross-build for Scala 2.13.

**Comment by vpavkin** [comment]
If anyone needs a separate release of circe-magnolia based on alternative magnolia build - feel free to ping me, I'll make one :)

**Comment by adamw** [comment]
Released 0.11.0 for 2.12 and 2.13
