### ISSUE TITLE
magnolia crashes scala on missing Option implicits

### ISSUE THREAD

**Issue by svalaskevicius** [propensive/magnolia#154]
I had a missing implicit for `Option[Int]` for a serialiser typeclass I'm writing, 
instead of failing the implicit resolution for the top level data type that includes it, I got 2535 lines of scala compiler error, summarised by:

```
[error] (Compile / compileIncremental) java.lang.AssertionError: assertion failed:                                                                                            
[error]   new SerialVersionUID(value = 5066590221178148012L)                                                                                                                  
[error]      while compiling: <...>                    
[error]         during phase: superaccessors
[error]      library version: version 2.12.8
[error]     compiler version: version 2.12.8
```

Once the `Option[A]` implicit has been added this was fixed.

Looking at those many lines, it does seem that it tries to auto-magic it somehow?

```
TREE: magnolia.Magnolia.subtype[com.svalaskevicius.<...>.JsonSerialiser.Typeclass, Option[Int], None.type](magnolia.TypeName.apply("scala", "None"), 0, scala.Array.apply[Any](new SerialVersionUID(value = 5066590221178148012L))((ClassTag.Any: scala.reflect.ClassTag[Any])), magnolia.CallByNeed.apply[com.svalaskevicius.<...>.JsonSerialiser[None.type]]({
```

**Comment by svalaskevicius** [comment]
Btw, apart from a few solvable issues, magnolia's interface does seem very nice! I like how easy it is to derive typeclass instances :) thanks!

**Comment by andrewsmartin** [comment]
I've run into this issue as well with Option types. @svalaskevicius were you able to find some workaround to make the compiler fail with the expected `ImplicitNotFound` instead?

**Comment by svalaskevicius** [comment]
@andrewsmartin, no.. I've only played with it on a pet project so far, and haven't had a chance to look deeper..

**Comment by adamw** [comment]
Got the same. Veeery long error. Here's my typeclass (nothing fancy, basically schema information copied from the case class structure):

https://github.com/softwaremill/tapir/blob/master/core/src/main/scala/tapir/generic/SchemaForMagnoliaDerivation.scala

And here's the code which causes the error to happen:

**Comment by ghostdogpr** [comment]
Ran into this error as well 😄 

@adamw thanks for sharing, my usecase was similar to yours and I thought there was an issue with my `List` instance, but your comment made me realize it was something within the item type.

**Comment by kubukoz** [comment]
Aaaaand I'm joining this thread of happy users who got this, this time with https://github.com/softwaremill/diffx, so I'll tag in @ghostbuster91 as well...

**Comment by joroKr21** [comment]
Do we have a standalone reproduction? It would really help.

**Comment by adamw** [comment]
@joroKr21 maybe that's the same issue as here: https://github.com/propensive/magnolia/issues/178 ?

**Comment by ghostdogpr** [comment]
Here's a simple reproducer (with scala 2.12, magnolia 0.11): https://gist.github.com/ghostdogpr/0dcc6e87df86a3a476f8b6f6674b4c92 (initially made it in scastie but the 2k-lines compiler crash made scastie crash 😅)

**Comment by joroKr21** [comment]
The crash is just a symptom. The stack is not being popped on error after chained implicit.

**Comment by joroKr21** [comment]
Minimized reproduction:
```scala
import magnolia.examples.Show

object Test extends App {
  @SerialVersionUID(42) case class SomeClass(others: Seq[Another])
  case class Another(label: Byte)
  Show.gen[SomeClass]
}
```

**Comment by joroKr21** [comment]
The problem is that if we do pop the stack we lose context for the error messages.
Very tricky.
