### ISSUE TITLE
Derivation is disabled

### ISSUE THREAD

**Issue by ngthanhtrung** [propensive/magnolia#16]
As I can see [here](https://github.com/propensive/magnolia/blob/8cd72499b92d745ce3e3f2621a03ab61ce78ef85/core/src/main/scala/magnolia.scala#L202), `Derivation` case is not implemented. Is there any special reason to do so?

**Comment by propensive** [comment]
So, that was work-in-progress, and the API has completely changed since then. If you try again now, you should find that derivation works for both covariant and contravariant typeclasses (using the same API, now).

**Comment by ngthanhtrung** [comment]
Thanks!
