### ISSUE TITLE
Release for Scala 2.13.0-RC1

### ISSUE THREAD

**Issue by sirthias** [propensive/magnolia#162]

**Comment by sksamuel** [comment]
2.13.0 final now.

**Comment by rgugliel** [comment]
What is the status ?

I'd like to help but master does not compile on my machine...
Since Mercator is a dependency, I opened the following: https://github.com/propensive/mercator/pull/10

**Comment by adamw** [comment]
0.11.0 is released for 2.12 and 2.13

**Comment by francisdb** [comment]
@adamw under what groupId/artifactId?

**Comment by adamw** [comment]
@francisdb `com.propensive` and `magnolia`: http://repo1.maven.org/maven2/com/propensive/magnolia_2.12/0.11.0/
