### ISSUE TITLE
isValueClass predicate is broken

### ISSUE THREAD

**Issue by eld0727** [propensive/magnolia#165]
Current way of `isValueClass` calculation gives false positive results on refinements.
It becomes true on the next type
```
<refinement of Int with supertagged.Tag[Int,domain.tagged.Zoom.Tag]>
```

It is a tag type from supertagged library

That leads macro expansion to line 74 of globalutil.scala file
```scala
global.gen.mkAttributedRef(globalType.prefix, companion).asInstanceOf[c.Tree]
```

And then compiler prints next error to console:
```
bad qualifier received: mkAttributedQualifier(<notype>, <none>)
```

**Comment by joroKr21** [comment]
> Current way of isValueClass calculation gives false positive results on refinements.

Unfortunately I don't think `isRefinementClass` is exposed as a macro API

About `globalutil.scala` - I don't know if anyone here understands it. It's just some copy pasta hack.
