### ISSUE TITLE
Java annotations "fix" fails to compile for 2.11

### ISSUE THREAD

**Issue by adamw** [propensive/magnolia#169]
`isJavaAnnotation` is available since 2.12. This seems to do the trick:

```
val isJavaAnnotation: Tree => Boolean = _.tpe.typeSymbol.asInstanceOf[scala.reflect.internal.HasFlags].hasJavaAnnotationFlag
```

See: https://github.com/adamw/magnolia/commit/4cae03554cca00263deefb0db7591f81d22905c4
(the examples still fail to compile, though)

This is released as `"com.softwaremill" %% "magnolia" % "0.11.1-sml"`

**Comment by kubukoz** [comment]
Fixed in https://github.com/propensive/magnolia/pull/168 :)

**Comment by adamw** [comment]
Ah :D we can now choose which hack is better ;)

Unfortunately I didn't notice this before, would have saved me some time. Anyway, the above version is released (and used e.g. in tapir)
