### ISSUE TITLE
Bring back 2.11 support?

### ISSUE THREAD

**Issue by nevillelyh** [propensive/magnolia#171]
First, thanks for the new release.

This is a general question as how hard is it to bring back 2.11 support and if you guys are open to it if someone contributes a PR. I'm asking since a lot of data pipelines are still on 2.11 because of Spark or other complications.

**Comment by nevillelyh** [comment]
Also wondering if #157 is the only blocker and if it can be worked around.

**Comment by joroKr21** [comment]
No, there is a deeper issue with lazy vals encoding in 2.11 and this line:
https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L501

We had a discussion about it on some issue a long time ago but I couldn't find it right now.

**Comment by joroKr21** [comment]
Ah here it is: #78

**Comment by afsalthaj** [comment]
Currently Magnolia is being used in zio-config and apparently, we had to remove 2.11 support as well. It will be a great help for the users to get back the support of 2.11 for some more time.

**Comment by propensive** [comment]
Who are these users of Scala 2.11? ;) I just reread the discussion on #78 (which I had forgotten) and it seems like it would be disproportionately hard to fix. Not impossible, certainly, but not a high priority.

We haven't had support for Scala 2.11 for nearly two years, and it doesn't seem like the right time to bring it back now. I'm actually happy to be adding a little bit more pressure to the ecosystem to move off unmaintained versions of Scala, so I'll close this issue. There is still an old version of Magnolia published for 2.11, which should be usable.
