### ISSUE TITLE
compilation error with assertion failed

### ISSUE THREAD

**Issue by yanns** [propensive/magnolia#175]
While trying to use magnolia on a quite important project, I got a compilation error like that one:
```
[error] (Compile / compileIncremental) java.lang.AssertionError: assertion failed:
[error]   new SerialVersionUID(value = 509929039250432923L)
[error]      while compiling: /[...].scala
[error]         during phase: superaccessors
[error]      library version: version 2.12.10
[error]     compiler version: version 2.12.10
```

The error is much longer, and outputs the code generated by the macro.
Any idea where should I look to try to find the issue?

**Comment by joroKr21** [comment]
I guess it would be helpful if you can post the full error.
Or if you have a self contained minimization post that.
The problem is that the assertion error probably comes from within `scalac` when it tries to compile the generated code. Things like this can happen if the macro has a bug or an edge case it can't handle.

**Comment by yanns** [comment]
I have no explanation, but I found out that removing the implicit on the `gen` fixes this issue.
After that, I have a normal expected error like:
```
magnolia: could not find MongoFormat.Typeclass for type XXXX
```

**Comment by yanns** [comment]
I close this ticket.
I don't manage to have a minimization.

**Comment by yanns** [comment]
Is there a reason why the `gen` is implicit in https://propensive.com/opensource/magnolia/#usage?

**Comment by joroKr21** [comment]
It's definitely intended to work both as `implicit` and as not `implicit`
