### ISSUE TITLE
Fails to derive typeclass instance for recursive class when referenced

### ISSUE THREAD

**Issue by ghostbuster91** [propensive/magnolia#178]
Given recursive class RPerson - 
`case class RPerson(age: Int, name: String, child: Option[RPerson])`
derivation will work.

But it will fail as soon as we create another class which references the recursive class wrapping the reference with the same container as is used within the recursive class, e.g.
`case class GPerson(child: Option[RPerson])`

It doesn't matter if the container is an option/either/list or anything like that, but it has to be the same in both recursive class and the other one.

Here is a gist with the full example: https://gist.github.com/ghostbuster91/1e09a8d9fa9ca3d2ff99df0db732bdc4

**Comment by joroKr21** [comment]
Second commit of #179 fixes this
