### ISSUE TITLE
Magnolia website font is hard to read

### ISSUE THREAD

**Issue by jozic** [propensive/magnolia#18]
While it looks very nice, it's hard to read. Please consider to change it. Thanks

**Comment by propensive** [comment]
Thanks for the suggestion. So as not to compromise the design, I could do what I did with https://scala.world/ and offer a button to switch to an easy-to-read font.

**Comment by jozic** [comment]
that would be great

**Comment by propensive** [comment]
Still ongoing work in progress on the website, but this issue is fixed now. :)

**Comment by jozic** [comment]
thanks!
