### ISSUE TITLE
Accumulating errors in decoder-like type classes

### ISSUE THREAD

**Issue by ruippeixotog** [propensive/magnolia#181]
For decoder-like type classes it's often useful to report errors for all failing fields of a case class, not only for the first one. In PureConfig we use an `Either[ConfigReaderFailures, A]` to accumulate failures and I'd like to reproduce this behavior without having to fall back to `rawConstruct`. Am I correct in assuming there is no current workaround for this?

How difficult would it be to provide a `constructApplicative`? One challenge would be to generate instances automatically like Magnolia does with Mercator, but I'd be happy with users having to provide their own instances.

**Comment by jto** [comment]
Hi @ruippeixotog.

Not sure I follow. If I understand what you are talking about, it should be possible to simply accumulate the errors in the implementation of `combine`. 

Am I missing something ?

**Comment by ruippeixotog** [comment]
My type class is something like this, basically:

```scala
trait Reader[A] {
  def from(conf: Config): Either[NonEmptyList[Failure], A]
}
```

When building a `combine` method for this, a type-safe method like `constructMonadic` (constructing a product by specifying how to read each field while sequencing monads) is a good candidate. However, if I use `constructMonadic` the process is stopped when the first error occurs, preventing me from having access to all errors.

My case is akin to cats's `ValidatedNec` (nice tutorial with examples [here](https://typelevel.org/cats/datatypes/validated.html#meeting-applicative)). I want to try reading all fields and either:
- Construct the product inside a `Right` if all fields were successful;
- Have a non-empty collection of errors if at least one field failed.

`rawConstruct` is an escape hatch for me, but it's an unsafe API I'd prefer to avoid. What would be your suggestion to have this?

**Comment by joroKr21** [comment]
Interesting use case, that could benefit from `constructApplicative`

**Comment by jto** [comment]
Thanks for the more detailed example. Yeah I think `constructApplicative` is an interesting addition to the lib. 

Would one of you like to submit a PR  ?

**Comment by ruippeixotog** [comment]
That's good to know, but what would you propose doing here? The `Monadic` instances that power `constructMonadic` are auto-generated by [mercator](https://github.com/propensive/mercator), but it only handles monads - understandably, as it leverages Scala conventions of defining `map` and `flatMap`. Things are more complicated with applicative as there is no common Scala method with those semantics.

I can define `constructApplicative` with a new `Applicative` type class, but users would have to define their own instances before they'd be able to use the method (at least for now). I'd be ok with that - would that work for you too?

**Comment by joroKr21** [comment]
Ah, I didn't realize this about mercator

**Comment by pjrt** [comment]
I had the same issue, I tried adding an `ap` to Monadic in Mercantor (you can define `ap` from `flatMap`, after all). However sadly I kind of got stuck in magnolia. My Scala macro knowledge is a bit lacking.
