### ISSUE TITLE
SealedTraits are not listed in stable order

### ISSUE THREAD

**Issue by jfwilson** [propensive/magnolia#195]
Currently the ordering of sealed trait types is based on `ClassSymbol.knownDirectSubclasses.toList` (see [src/main/scala/magnolia.scala#L129](https://github.com/propensive/magnolia/blob/24e18384666b60eba9119c9de00f97afc4d129cb/core/shared/src/main/scala/magnolia.scala#L129)).

`knownDirectSubclasses` is a `Set` with unspecified ordering (dependent on hash algorithms and the order in which the compiler visits types), and so the results of `toList`-ing it can change unexpectedly (i.e. can change even if the order they are declared in the code remains unchanged).

How much this is a problem obviously depends on the use case, but imho it would be better to expose these in a stable order. Suggest alphabetically sorted based on fullName, this would have the benefit of being stable against reordering the code and would match the logic in [Shapeless Generic](https://github.com/milessabin/shapeless/blob/ab5a1a6bb1e01e13fd417e0ee0d8726d54344d84/core/src/main/scala/shapeless/generic.scala#L423).

**Comment by joroKr21** [comment]
The other option would be by position. I have no strong feelings one way or the other.
And given that `shapeless` is much older perhaps using the same order would make it less surprising when exchanging one derivation scheme for the other.
So I'm :+1: on the alphabetic ordering.

Want to make a PR?
