### ISSUE TITLE
performance idea for derived coproduct

### ISSUE THREAD

**Issue by fommil** [propensive/magnolia#2]
you seem to have solved every issue I have with shapeless typeclass derivation, so going one further... @andyscott has a nice hack in freestyle and iota that allows using `@switch` instead of going through each coproduct one at a time.

I have no idea how you'd do it, I'm basically waving my hands at this point, LOOK A CHART!

![https://www.47deg.com/assets/img/blog/2017-05-10_iota_bench.png](https://www.47deg.com/assets/img/blog/2017-05-10_iota_bench.png)

**Comment by propensive** [comment]
I've no idea if this will work as desired, but I'm now using `@switch`.

https://github.com/propensive/magnolia/pull/5

**Comment by propensive** [comment]
Merged, and awaiting some sort of testing...
