### ISSUE TITLE
Provide better support for `TupleN`

### ISSUE THREAD

**Issue by propensive** [propensive/magnolia#20]
Tuples behave mostly like case classes, though there may be some subtle differences which mean they don't work. They haven't been tested yet.

**Comment by entangled90** [comment]
what do you think the API should look like?
After a brief analysis the easiest thing to do i probably add a field to `CaseClass`:
```
abstract class CaseClass[Typeclass[_], Type] (
  val typeName: TypeName,
  val isObject: Boolean,
  val isValueClass: Boolean,
  val isTuple: Boolean,
  parametersArray: Array[Param[Typeclass, Type]],
  annotationsArray: Array[Any]
)
```

**Comment by jto** [comment]
@propensive should we close this issue ?

**Comment by joroKr21** [comment]
We can keep it to track if anyone wants an `isTuple` flag, though it doesn't seem to be the case.

**Comment by propensive** [comment]
I think we can close it.
