### ISSUE TITLE
Publish artifact for ScalaJS 1.0.0-RC2

### ISSUE THREAD

**Issue by lvitaly** [propensive/magnolia#205]
It would be great to publish the latest magnolia artifact for ScalaJS 1.0.0-RC2 to give a chance for other projects to adopt for ScalaJS 1.0.0 release earlier.

**Comment by propensive** [comment]
I don't think there should be anything stopping us... Support for ScalaJS is already in the SBT build. If you create a PR with the new versions, and check that they work, I'm happy to merge it and run the release process. :)

**Comment by xuwei-k** [comment]
https://github.com/propensive/magnolia/pull/210
