### ISSUE TITLE
lazy val leads to illegal premature access error.

### ISSUE THREAD

**Issue by VladPodilnyk** [propensive/magnolia#214]
This could be related to the following closed issue (https://github.com/propensive/magnolia/issues/95)

I've came up with code example which partially based on `magnolia`'s examples. Full showcase repo could be found [here](https://github.com/VladPodilnyk/magnolia-exper).

Based o such trait and derivation rules:
```scala
trait Decoder[T] {
  def decode(value: String): T
}

object Decoder {
  /** decodes strings */
  implicit val string: Decoder[String] = (s: String) => s

  /** decodes ints */
  implicit val int: Decoder[Int] = _.toInt

  def gen[T]: Decoder[T] = macro Magnolia.gen[T]

  type Typeclass[T] = Decoder[T]

  def combine[T](ctx: CaseClass[Decoder, T]): Decoder[T] = value => {
    val (_, values) = parse(value)
    ctx.construct {
      param =>
        param.typeclass.decode(values(param.label))
    }
  }

  def dispatch[T](ctx: SealedTrait[Decoder, T]): Decoder[T] = param => {
    val (name, _) = parse(param)
    val subtype   = ctx.subtypes.find(_.typeName.full == name).get
    subtype.typeclass.decode(param)
  }

  private def parse(value: String): (String, Map[String, String]) = ???
}
```
I am trying to provide a convenient type `WithDecoder` which contains `implicit val dec: Decoder[T]`. I've described `WithDecoder` as follows
```scala
abstract class WithDecoder[T]()(implicit decoder: MaterializedDecoder[T]) {
  implicit val dec: Decoder[T] = decoder.value
}

final class MaterializeDerivationMacros(val c: blackbox.Context) {
  import c.universe._

  def materializer[T: c.WeakTypeTag]: c.Expr[MaterializedDecoder[T]] = c.Expr[MaterializedDecoder[T]] {
    q"{ new ${weakTypeOf[MaterializedDecoder[T]]}(_root_.issue.Decoder.gen[${weakTypeOf[T]}]) }"
  }
}

final case class MaterializedDecoder[T](value: Decoder[T])
object MaterializedDecoder {
  implicit def materialize[T]: MaterializedDecoder[T] = macro MaterializeDerivationMacros.materializer[T]
}
``` 

When I've tried to compile the following code snippet, compile throws an error
```scala
object models {
  case class Test(s: String)
  object Test extends WithDecoder[Test]
}
```

```
Error:(5, 23) Implementation restriction: access of lazy value paramTypeclass$macro$3$1 in object Test from <$anon: Function0>, would require illegal premature access to object Test in object models
  object Test extends WithDecoder[Test]
```

So, the question is there any way to fix this?
Could somebody help with that?

**Comment by propensive** [comment]
Wow, that looks hairy... :( Thanks for the clear bug report, though.

I don't remember enough about #95 to give an authoritative answer, but maybe @joroKr21 does. Do you think you could experiment with reverting #96 in Magnolia, or changing that `val` to a `def` instead, and seeing if that makes any difference?

**Comment by vpodlnk** [comment]
@propensive, yep, I could play around. I'll let you know if those changes make any difference.

**Comment by VladPodilnyk** [comment]
@propensive, yep, I could play around. I'll let you know if those changes make any difference.

**Comment by joroKr21** [comment]
I'm afraid this won't work. You can't define an object that references itself in the extends clause.
And the companion object is referenced in any typeclass generated by Magnolia.

The error message is misleading but I believe it hides a fundamental restriction.
Shapeless has the same problem. Here is an example using vanilla Scala:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

trait Default[A] {
  def default: A
}

object Default {
  def instance[A](value: A): Default[A] = new Default[A] {
    def default = value
  }
}

abstract class WithDefault[A](instance: Default[A]) {
  implicit def default: Default[A] = instance
}

case class Test(s: String)
object Test extends WithDefault(Default.instance(Test("")))

// Exiting paste mode, now interpreting.


object Test extends WithDefault(Default.instance(Test("")))
                                                 ^
<pastie>:16: error: illegal cyclic reference involving object Test

object Test extends WithDefault(Default.instance(Test("")))
                    ^
<pastie>:16: error: illegal inheritance;
 self-type Test.type does not conform to WithDefault[Test]'s selftype WithDefault[Test]

object Test extends WithDefault(Default.instance(Test("")))
                                                ^
<pastie>:16: error: no arguments allowed for nullary constructor Object: ()Object
```

**Comment by joroKr21** [comment]
I was wrong - we don't actually need a reference to the companion object: #219
I suspect when you say `object Test extends WithDecoder[Test]` `WithDecoder` finds the implicit `Test.dec` (i.e. itself) and creating a loop.

**Comment by VladPodilnyk** [comment]
hi, @joroKr21, thanks a lot  for your answers. What I've found is that if I return just `val` in this place https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L190
(I've just replaced this)
```scala
if (!fullauto || shouldBeLazy) q"lazy val $name: $tpe = $rhs"
      else q"val $name = $rhs"
```
with 
```scala
q"val $name = $rhs"
```
the example project will compile.


But it looks like you've already found the cause.

**Comment by joroKr21** [comment]
Hi, no I haven't found the reason. Although now that you mention it the condition looks suspicious.
Why is it lazy if `!fullauto`? My guess is that it should be lazy only when... well `shouldBeLazy`.
