### ISSUE TITLE
Please Release 0.13.0

### ISSUE THREAD

**Issue by neko-kai** [propensive/magnolia#223]
Release `0.13.0` failed to publish, it's not available on maven central: https://search.maven.org/artifact/com.propensive/magnolia_2.13

**Comment by joroKr21** [comment]
Maybe worth it to invest some time to setup `sbt-ci-release`

**Comment by propensive** [comment]
I'm not sure why we didn't get 0.13.0, but we now have 0.13.1 and 0.14.0 and soon 0.14.1...
