### ISSUE TITLE
Derivation does not work with value case classes

### ISSUE THREAD

**Issue by iRevive** [propensive/magnolia#225]
Magnolia version: `0.13.1`
Scala version: `2.13.1`

Code snippet:
```scala
final case class ServiceName1(value: String) extends AnyVal

test("derive for a value class") {
  val showServiceName: Show[String, ServiceName1] = Show.gen[ServiceName1]
  showServiceName.show(ServiceName1("service"))
}.assert(_ == "service")
```

Compilation error:
```
too many arguments (2) for constructor ServiceName1: (value: String)magnolia.tests.ServiceName1
[error]       val showServiceName: Show[String, ServiceName1] = Show.gen[ServiceName1]
```

Seems the functionality was broken in the scope of #215 MR: https://github.com/propensive/magnolia/pull/218

**Comment by iRevive** [comment]
Highly likely the condition is incorrect for the value **case classes**  https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L286, but I'm unable to find out what is exactly wrong.

**Comment by joroKr21** [comment]
Thanks, unfortunate that we didn't have a test case for this 😞
