### ISSUE TITLE
Meeting to discuss Magnolia's future

### ISSUE THREAD

**Issue by propensive** [propensive/magnolia#241]
__Agenda__
- Cleaning up GitHub issues and missing features
- Making the `fury` branch the default
- Stability of API and releases
- Requirements for version 1.0
- Migration strategy for Scala 3

Please leave a note here if you would be interested in taking part in the meeting. It would help if you could DM your email address to `@propensive` in advance so I can send you a calendar invitation.

**Comment by adamw** [comment]
interested :)

**Comment by joroKr21** [comment]
me too 👍

**Comment by yanns** [comment]
interested as well.

**Comment by kubukoz** [comment]
Interested!

**Comment by jto** [comment]
Me too :)

**Comment by nevillelyh** [comment]
+moi :)

**Comment by mikearnaldi** [comment]
interested

**Comment by softinio** [comment]
Interested for sure count me in Sir 👍 Thank you 🙏

**Comment by idreeskhan** [comment]
Interested, thanks

**Comment by nmcb** [comment]
Not really certain whats at stake, but yes, nice.

An interested observer.

**Comment by landerlo** [comment]
Would love to attend. I toyed with adding support for alternative "helper" typeclasses but it was adding too much complication to it and I've started my own design.

**Comment by ghostbuster91** [comment]
Count me in

**Comment by adamgfraser** [comment]
Interested.

**Comment by regadas** [comment]
interested! Thanks

**Comment by astefanich** [comment]
interested in contributing, thx

**Comment by propensive** [comment]
Thanks for replying everyone! I've sent everyone* three calendar invitations for meetings on three days next week. (Tuesday, Wednesday, Thursday evenings, in Europe at least.) Please accept _all_ of the times that you could potentially attend. I will remove two of the options on Sunday so that by the start of next week we will have settled on a date/time.

* If you didn't get the invitation, it's because I have the wrong or no email address for you! Please send me a Twitter DM to `@propensive` or email me at `jon.pretty@propensive.com` to let me know. I may also have accidentally missed someone off. I know in particular that I couldn't find email addresses for @softnio or @mikearnaldi.

**Comment by kubukoz** [comment]
As one of the outputs, we decided to have someone try using getting Magnolia to provide a high-level API over Scala 3's typeclass derivation - I tried the new derivation mechanism yesterday and would like to take on this challenge (at least to identify any major roadblocks) sometime soon. :)

**Comment by propensive** [comment]
Awesome, let's have a chat about it some time!

**Comment by propensive** [comment]
I'm going to close this issue before it becomes a general discussion area...
