### ISSUE TITLE
Check in knownSubclasses that all subtraits are sealed

### ISSUE THREAD

**Issue by yanns** [propensive/magnolia#243]
I'm wondering if we should support the following code:
```
  sealed trait Color7
  trait Color7a extends Color7
  object Color7 {
    case object Red extends Color7a
    case class Custom(rgb: String) extends Color7a
  }
```

By deriving `Color7`, magnolia throws a compilation error:
```
magnolia: could not find any direct subtypes of trait Color7
```
Is it a use-case we should support?

**Comment by joroKr21** [comment]
But `Color7a` is not sealed which would make it an escape hatch.
Otherwise we already handle hierarchies:
```scala
    def knownSubclasses(sym: ClassSymbol): Set[Symbol] = {
      val children = sym.knownDirectSubclasses
      val (abstractTypes, concreteTypes) = children.partition(_.isAbstract)
      abstractTypes.map(_.asClass).flatMap(knownSubclasses(_)) ++ concreteTypes
    }
```

**Comment by joroKr21** [comment]
Looks like this code needs to be made stricter

**Comment by yanns** [comment]
Thx for the update.
I've tested with:
```
  sealed trait Color7
  sealed trait Color7a extends Color7
  object Color7 {
    case object Red extends Color7a
    case class Custom(rgb: String) extends Color7a
  }
```

and it's working as expected.
thx!

**Comment by joroKr21** [comment]
If you don't mind I'll repurpose this issue to add a check that all subtraits are sealed and give a better error message.

**Comment by yanns** [comment]
> If you don't mind I'll repurpose this issue to add a check that all subtraits are sealed and give a better error message.

that would be awesome!
