### ISSUE TITLE
Macro crashes when polymorphic default constructor arguments types are mismatched

### ISSUE THREAD

**Issue by ncreep** [propensive/magnolia#244]
Hi,

I've recently discovered a curious fact about default values in Scala. In the presence of type parameters, the default value can be a specific type. For example:
```scala
case class Foo[A](value: A = 3)
```
Although `value` is a generic type, it's perfectly fine to assign an `Int` as its default value. Typechecking is deferred to the actual instantiation of `Foo`.

This causes problems for Magnolia...

Invoking the Magnolia macro when there is a mismatch between the default argument's type and the actual expected type causes the macro to crash with an exception.

Given the following minimal set up:
```scala
import magnolia.{CaseClass, Magnolia}
import scala.language.experimental.macros

trait Dummy[A]

object Dummy {
  implicit val dummyForString: Dummy[String] = new Dummy[String] {}

  type Typeclass[A] = Dummy[A]

  def combine[A](caseClass: CaseClass[Typeclass, A]): Typeclass[A] =
    new Dummy[A] {}

  implicit def gen[A]: Typeclass[A] = macro Magnolia.gen[A]
}
```

Compiling this:
```scala
case class Foo[A](value: A = 3)

object DummyTest {
  Dummy.gen[Foo[String]]
}
```

Crashes with:
```
[error] test/DummyTest.scala:6:12: exception during macro expansion:
[error] scala.reflect.macros.TypecheckException: type mismatch;
[error]  found   : Int
[error]  required: String
[error]         at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:44)
[error]         at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:38)
[error]         at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:37)
[error]         at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$7(Typers.scala:50)
[error]         at scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1756)
[error]         at scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1753)
[error]         at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:28)
[error]         at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:50)
[error]         at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:32)
[error]         at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error]         at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
[error]         at magnolia.Magnolia$.$anonfun$gen$58(magnolia.scala:376)
[error]         ...
[error]   Dummy.gen[Foo[String]]
[error]            ^
[error] one error found
```
The culprit is an invocation of an intentional typecheck during macro expansion [here](https://github.com/propensive/magnolia/blob/357a29aaea258a0bc452e5d51d71b84c0da75c59/core/shared/src/main/scala/magnolia.scala#L376):
```scala
val dummyArgs = params.filterNot(_.isParamWithDefault).map(p => q"${p.name} = $x")
// `A <: Nothing` to avoid dead code warnings
val dummy = c.typecheck(q"def $x[$A <: $scalaPkg.Nothing]($x: $A) = new $genericType(..$dummyArgs)")
```

The second line throws an exception and crashes the macro.

Ideally, I think that in such a mismatch, it should be considered that the default value is absent.

Will you be open to accept a patch to fix this issue? If so, pointers as to how to tackle it will be greatly appreciated (the mechanics of the code quoted above are a bit opaque to me).

Thanks

**Comment by joroKr21** [comment]
Hi @ncreep a fix would certainly be accepted.
I don't have any pointers at the moment how it would look like.

I can explain the mechanics of the code above.

We create a constructor call `new Foo(a = x, b = x, c = x)` for all parameters (`a, b, c`) that don't have a default value. `x` here is a dummy with type `Nothing` so we can substitute it for anything. Well it's a bit more complicated as you see to avoid dead code warnings.

After we typecheck this constructor call, the compiler inserts the default arguments for the remaining parameters - and we can extract them from the resulting tree. These gymnastics are necessary because we haven't found a better way to access the default arguments.

**Comment by joroKr21** [comment]
The problem is that you can't check that the types don't match before obtaining the default value and you can't obtain the default value before typechecking. And typechecking fails because the types don't match. So perhaps the best we can do is to catch the error and provide a better error message.

**Comment by ncreep** [comment]
Well, I've seen other approaches to getting a handle on the default arguments, that do it one-by-one. For example, [this](https://github.com/iheartradio/ficus/blob/155c4ca5596b44cd9855dcca95406c1c19b512a6/src/main/scala/net/ceedubs/ficus/readers/ArbitraryTypeReader.scala#L79). Is there any reason to think that it can't work out for Magnolia as well?

As for just improving the error message for this case. In my specific use-case, it'll suffice to just ignore the default arguments rather than erroring-out (maybe emit a warning). Is this an acceptable approach, or hiding errors this way will be too confusing for users?

**Comment by joroKr21** [comment]
> I've seen other approaches to getting a handle on the default arguments, that do it one-by-one. For example, this. Is there any reason to think that it can't work out for Magnolia as well?

`companion` is buggy. We used to do it this way but look at the horrible hack we had:
https://github.com/propensive/magnolia/pull/219/files#diff-d10f395adc80ba75bb7634617a7c0e7a

I thought of another way though - walk the owner chain of the case class and the current owner chain until you find a common owner. This will let you construct a reference to the companion object without having the symbol. And then you will have to compare the types.

> As for just improving the error message for this case. In my specific use-case, it'll suffice to just ignore the default arguments rather than erroring-out (maybe emit a warning). Is this an acceptable approach, or hiding errors this way will be too confusing for users?

I think that's acceptable with a warning. 👍

**Comment by ncreep** [comment]
I think I have an approach that circumvents the problem, while not doing anything too clever beyond what's already there.

Instead of creating a list of dummy arguments only for the non-default parameters, I'll create a list of dummies standing in for all arguments. Then, for each default parameter at index `i`, omit `i` from the dummies list. Run the current code on this new list to extract the one default argument there.

This way, I'm checking one argument at a time, if it compiles fine, if not I omit it and move on (maybe with a warning).

The price I'm paying is the possibility of being quadratic in the number of arguments. Not sure whether it matters, but if it does, it's possible to keep the old code for the "happy path" and only apply the logic above when the old approach fails.

I have a messy sketch of this approach, and it seems to be okay. Will try to open a pull request in the coming days.

**Comment by joroKr21** [comment]
> The price I'm paying is the possibility of being quadratic in the number of arguments as well as more typechecking runs. Not sure whether it matters, but if it does, it's possible to keep the old code for the "happy path" and only apply the logic above when the old approach fails.

Yep that would be too expensive. We really try to keep the compile times down in Magnolia.
It's a major goal of the project.

**Comment by ncreep** [comment]
You beat me to it...
I guess your way is better anyways. Thanks for the quick turnaround.

Is there a snapshot release that  I can depend on with the changes from #250?

**Comment by joroKr21** [comment]
I'm not sure if we publish snapshots
