### ISSUE TITLE
add documentation to ensure `scala-reflect` is included on the classpath

### ISSUE THREAD

**Issue by ScalaWilliam** [propensive/magnolia#245]
Hi, I'm trying out the latest version of this library with Scala 2.13.2 and get this error. Same with Scala 2.13.1 and 2.12.11.

```
src/main/scala/csv.scala:24:54: macro implementations cannot have implicit parameters other than WeakTypeTag evidences
[error]   implicit def deriveCsv[A]: Csv[A] = macro Magnolia.gen[A]
[error]                                                      ^
```

Test repository: https://github.com/ScalaWilliam/mag-test
Source code is copy-paste of 
https://github.com/propensive/magnolia/blob/master/examples/shared/src/main/scala/csv.scala

Adding this fixes it:
```
libraryDependencies += "org.scala-lang" % "scala-reflect" % scalaVersion.value
```

For anyone experiencing this issue, I did not see it mentioned in the docs.

**Comment by propensive** [comment]
Thanks for the report, @ScalaWilliam! It seems very odd (given what I know about the implementation of the macro not having any other implicits), and I've not seen it before, but the fix hints at the problem: it looks like the version of `scala-reflect` (which provides the `WeakTypeTag` type) used to compile Magnolia is different from the version being used to expand the macro, and the implicit `WeakTypeTag` that we ask for appears (to the compiler doing the macro expansion) not to be a `WeakTypeTag`, at least not the one it was expecting.

I think this must be a mismatch between a Scala 2.12 `scala-reflect` and a Scala 2.13 `scala-reflect`. The others should be binary compatible.

Is there any chance that the there could be a rogue `scala-reflect` somewhere on the classpath?

(By the way, I didn't look at the repo yet...)

**Comment by propensive** [comment]
Ok, I did look at the repo now, which took me all of 20 seconds. ;) And obviously there's nothing unusual about the build...

Has anyone else seen anything like this?

**Comment by ScalaWilliam** [comment]
@propensive I tried to do it on Travis-CI, and the result was the same, so it appears reproducible:

https://travis-ci.org/github/ScalaWilliam/mag-test/builds/684419858#L420

**Comment by joroKr21** [comment]
So I'm not really sure about this but I think since we don't ship `scala-reflect` as a transitive dependency (on purpose) as a consequence users have to explicitly add it (but can benefit from having it at compile time only by appending `% "provided"`).

cc @neko-kai 

If this is the case then we need to put it in a central place in the README.

**Comment by neko-kai** [comment]
@joroKr21 Yeah, that's exactly what happens

**Comment by neko-kai** [comment]
You always need a (`Provided` ideally) dependency on scala-reflect wherever you define macros

**Comment by propensive** [comment]
I've updated the issue to reflect this. Thanks everyone.

**Comment by propensive** [comment]
I've updated the documentation [here](https://propensive.com/opensource/magnolia/tutorial).

**Comment by propensive** [comment]
By the way, I'll be moving this documentation into this repository quite soon. I would do it straight away, but I don't want to have two different sources of truth at the same time, so I'll do this at the same time as I update `propensive.com` to pull the docs from their forthcoming home in repository.

**Comment by joroKr21** [comment]
@propensive I couldn't fail to notice that you forgot to recommend adding `% Provided` 😄

**Comment by propensive** [comment]
Included it now, thanks! :)
