### ISSUE TITLE
Typename.typeArguments are lost in case of type alias

### ISSUE THREAD

**Issue by ivan-klass** [propensive/magnolia#259]
When the type requesting a typeclass is somehow simplified using an alias, the expanded type parameters are not propagated to `TypeName` properly.

Steps to reproduce:
[Scastie](https://scastie.scala-lang.org/GeBK33EyQiqiHEpOii3noQ)
[Gist](https://gist.github.com/ivan-klass/18239911298ea112f5b853c63621752d)

**Comment by joroKr21** [comment]
I'm not sure there is a right answer here. Others might as well expect the alias' name to be returned.
