### ISSUE TITLE
Fury layer for the latest version of Magnolia

### ISSUE THREAD

**Issue by odisseus** [propensive/magnolia#265]
## Progress
* I have [defined a layer](https://gateway.pinata.cloud/ipfs/QmZ5iJSHLXpPpW9KpKmTasVwMqtw2zo4YDiRboPWt8WdXo) that partially works:
  * It is based on my fork with [rearranged source directories](https://github.com/odisseus/magnolia/tree/fury-new);
  * The "core" and "examples" are compiling;
  * The "test" module is partially defined, but it is still missing important parts.

## Problems
* Magnolia tests depend on an old version of Probably (which was called Estrapade back at the time), and the recent version of Probably depends on Magnolia itself.
  * I have created a [provisional layer](http://gateway.pinata.cloud/ipfs/QmYEfSvoH4Gbz8Hf6q9Vbqp3BME6ooBqST24sRY8nqRosg) for the old Estrapade project. It seems to be working, but I haven't managed to get the Magnolia tests compiling so far.
  * This provisional layer is not compatible with Java 11, because the old code uses `java.xml.bind` classes.
* Magnolia tests depend on the string interpolators from Contextual's "data" module, but this module is not defined in the Contextual layer. See https://github.com/propensive/contextual/issues/58.
 * I have created a [provisional layer](https://gateway.pinata.cloud/ipfs/QmR1g39B9JNAZUu3mDovoKqmHTwv2Ui3BR1gehjcHEg161) which contains the data module.

**Comment by propensive** [comment]
This has all been cleaned up in the `main` branch now.
