### ISSUE TITLE
Import two derived typeclasses at once

### ISSUE THREAD

**Issue by xela85** [propensive/magnolia#271]
In order to bring configurable (auto/semiauto) derivation for Tapir, I would like to gather two different typeclass (`Schema`, `Validator`) derivations in a single `trait` or `package object` (like `Decoder` and `Encoder` in `io.circe.generic.auto._`). 

Unfortunately, I encounter the following error while trying to group derivations : 
```scala
package sttp.tapir.generic

import sttp.tapir.{Schema, Validator}
import sttp.tapir.schema.LowPrioritySchema
import sttp.tapir.validator.LowPriorityValidator

package object auto extends LowPriorityValidator with LowPrioritySchema {
  implicit def schema[T] : Derived[Schema[T]] = sttp.tapir.schema.auto.schemaForCaseClass // => macro MagnoliaDerivedMacro.derivedGen[T]
  implicit def validator[T] : Derived[Validator[T]] = sttp.tapir.validator.auto.validatorForCaseClass // => macro MagnoliaDerivedMacro.derivedGen[T]
}
```
```
[error] /Users/xela85/Dev/github/tapir/core/src/main/scala/sttp/tapir/generic/auto/package.scala:8:72: magnolia: could not infer package.Typeclass for type T
[error]   implicit def schema[T] : Derived[Schema[T]] = sttp.tapir.schema.auto.schemaForCaseClass
[error]
[error] /Users/xela85/Dev/github/tapir/core/src/main/scala/sttp/tapir/generic/auto/package.scala:9:81: magnolia: could not infer package.Typeclass for type T
[error]   implicit def validator[T] : Derived[Validator[T]] = sttp.tapir.validator.auto.validatorForCaseClass
```

Moreover, I can't use Magnolia's macro itself in the same trait as `dispatch` and `combine` method names clash.
in Is there a way to enable multiple imports of magnolia derived instances ? 

Thanks in advance

**Comment by joroKr21** [comment]
Doesn't importing both `sttp.tapir.schema.auto._` and `sttp.tapir.validator.auto._` work or do you want to have only one import?

**Comment by xela85** [comment]
Importing both packages effectively does the job. However I would prefer a smoother migration for users. Initially schemas and validators derivations were in companions and I find it a little annoying to import several packages in order to make everything compile.

**Comment by joroKr21** [comment]
Ok I agree that's a desirable use case but I don't know a way to make it work

**Comment by propensive** [comment]
I haven't looked in much detail, but would it be possible to put both `Schema` and `Validator` derivations into their corresponding companion objects, so that they're always visible through implicit scope, but "protected" through a dummy implicit that's in the `auto` package?

**Comment by xela85** [comment]
Clever trick ! It now works as I want, thank you !
