### ISSUE TITLE
[BUG] StackOverflowError when decoding enum with derived Schema

### ISSUE THREAD

**Issue by kubukoz** [propensive/magnolia#345]
Tapir version: 0.19.0-M4

Scala version: 3.0.1 / 3.1.0-RC2

**Describe the bug**

What is the problem?

A `StackOverflowError` gets thrown when you call an endpoint like this:

```scala
  enum Base derives Codec.AsObject, Schema {
    case EmptyImage
    // even this case isn't necessary to reproduce the issue
    case ImageReference(hash: String)
  }

  infallibleEndpoint
    .in("run")
    .post
    .in(jsonBody[Base])
```

**How to reproduce?**

Run the full code (ready sbt project in https://github.com/kubukoz/tapir-sooe-repro):

```scala
//scalaVersion := "3.1.0-RC2"
//libraryDependencies ++= Seq(
//  "org.http4s" %% "http4s-ember-server" % "0.23.4",
//  "com.softwaremill.sttp.tapir" %% "tapir-http4s-server" % "0.19.0-M9",
//  "com.softwaremill.sttp.tapir" %% "tapir-json-circe" % "0.19.0-M9",
//)

package demo

import cats.effect.IO
import cats.effect.IOApp
import com.comcast.ip4s.host
import com.comcast.ip4s.port
import io.circe.Codec
import org.http4s.HttpRoutes
import org.http4s.ember.server.EmberServerBuilder
import org.http4s.implicits._
import sttp.tapir.Schema
import sttp.tapir.server.http4s.Http4sServerInterpreter

object Main extends IOApp.Simple {

  enum Base derives Codec.AsObject, Schema {
    case EmptyImage
    // even this case isn't necessary to reproduce the issue
    case ImageReference(hash: String)
  }

  def run: IO[Unit] =
    EmberServerBuilder
      .default[IO]
      .withHost(host"0.0.0.0")
      .withPort(port"8083")
      .withHttpApp {
        import sttp.tapir._
        import sttp.tapir.json.circe._

        Http4sServerInterpreter[IO]()
          .toRoutes(
            infallibleEndpoint
              .in("run")
              .post
              .in(jsonBody[Base])
              .serverLogicInfallible(IO.println(_))
          )
          .orNotFound
      }
      .build
      .useForever

}
```

Call the endpoint:

```bash
curl -X POST localhost:8083/run --data {"EmptyImage":{}} -H Content-Type: application/json
```

See this in stderr of the program:

<details>
<summary>Stack trace</summary>

```
[0m[31m[E][0m java.lang.StackOverflowError
[0m[31m[E][0m 	at demo.Main$Base$.ordinal(Main.scala:18)
[0m[31m[E][0m 	at demo.Main$Base$.ordinal(Main.scala:18)
[0m[31m[E][0m 	at demo.Main$Base$.$anonfun$2(Main.scala:18)
[0m[31m[E][0m 	at magnolia.SealedTrait$Subtype.isDefinedAt(interface.scala:95)
[0m[31m[E][0m 	at magnolia.SealedTrait.rec$1(interface.scala:74)
[0m[31m[E][0m 	at magnolia.SealedTrait.choose(interface.scala:78)
[0m[31m[E][0m 	at demo.Main$$anon$3.$anonfun$3(Main.scala:18)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
// this repeats
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
// 
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:195)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$5(Schema.scala:194)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation(Schema.scala:194)
[0m[31m[E][0m 	at sttp.tapir.Schema.applyValidation$$anonfun$7(Schema.scala:195)
[0m[31m[E][0m 	at scala.Option.map(Option.scala:242)
```

</details>

**Additional information**

I think this might be a problem with Magnolia and not just Tapir, but I'm not sure. I also don't think Circe is related, I just happened to be using it. Didn't check if it's a http4s thing, but the stack trace doesn't suggest that.

This still happens if:
- the Codec or Schema instances are provided as `implicit def`/`implicit val`/`implicit lazy val`/`given` in the companion object of the enum
- the Codec instance is written by hand

This doesn't happen if:
- `Base` is an output type
- `Base` is a sealed trait hierarchy (even with `derives Schema`)
- The codec fails decoding (you just get a failed response instead, and the app keeps running)

**Comment by adamw** [comment]
@kubukoz yes done :)

I guess the problem is that `S` here is not a type, but a val. So these are *not* equivalent:

```scala
enum Size:
  case S
  case M(x: Int)

sealed trait Size2
object Size2 {
  case object S extends Size2
  case class M(x: Int) extends Size2
}
```

as if you print the types from the mirrors, you get:

```
TermRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class quicklens)),module class Size$)),val S), TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class quicklens)),module class Size$)),class M), 

TermRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class quicklens)),module class Size2$)),object S), TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class quicklens)),module class Size2$)),class M), 
```

(I was doing a quick test in quicklens, hence the parent)

**Comment by adamw** [comment]
See https://docs.scala-lang.org/scala3/reference/enums/desugarEnums.html

I wonder how we can properly represent such enums in magnolia then ... these are not really separate types, should we pretend otherwise?

**Comment by kubukoz** [comment]
S.type is still a singleton type, one could argue. IMO it should be represented in magnolia in the same way as usual case objects of a sealed trait hierarchy.

**Comment by KacperFKorban** [comment]
I think that I fixed the problem with wrong names #347

The problem with SOOE will probably require some minimization though

**Comment by adamw** [comment]
Thanks @KacperFKorban! That's a partial fix, unfortunately. The SOE is caused by the fact that the typeclass for the child (here the `val S`) is recursively the parent typeclass (here `Size`). Hence if there's any recursive operation involving nested typeclass instances, you get SOE as you loop endlessly traversing `Size`s children.

**Comment by adamw** [comment]
@kubukoz yes you're right, that's a good approach to this problem :) Maybe for no-parameter enum cases, we should also try to derive the typeclass for `S.type`?

**Comment by adamw** [comment]
Not sure if such derivation would default to an empty product, when derivation is done through magnolia (as it does with a `case object S`)

**Comment by joroKr21** [comment]
> The SOE is caused by the fact that the typeclass for the child (here the val S) is recursively the parent typeclass (here Size). Hence if there's any recursive operation involving nested typeclass instances, you get SOE as you loop endlessly traversing Sizes children.

That doesn't make sense - `Foo[Size]` is not the same as `Foo[S.type]`

**Comment by adamw** [comment]
> That doesn't make sense - Foo[Size] is not the same as Foo[S.type]

Exactly, but currently in case of a `enum Size { case S }`, `Subtype.typeclass` will lookup a typeclass for `Size`, not for `S.type`, ending up in infinite recursion

**Comment by joroKr21** [comment]
> Exactly, but currently in case of a enum Size { case S }, Subtype.typeclass will lookup a typeclass for Size, not for S.type, ending up in infinite recursion

Wouldn't that work only for contravariant type classes?

**Comment by adamw** [comment]
> Wouldn't that work only for contravariant type classes?

I don't think I understand?

If you have `sealed trait Size; object Size { case object S extends Size }` then the `Subtype.typeclass` corresponding to `Size.S` will lookup `Typeclass[Size.S]`, regardless of variance.

I think we should have something similar for enums?

**Comment by joroKr21** [comment]
> I think we should have something similar for enums?

Yeah but how do we end up looking up `Typeclass[Size]` and it typechecks in place of a `Typeclass[S.type]`?

**Comment by adamw** [comment]
> Yeah but how do we end up looking up Typeclass[Size] and it typechecks in place of a Typeclass[S.type]?

I haven't investigated in detail yet, but since `enum Size { case S }` is desugared into sth like `object Size { val S = new$(...) }`, the widened type for this value is `Size`. There is not type `S`.

**Comment by joroKr21** [comment]
`S.type` is in the mirror - see the `Opt` example here: https://dotty.epfl.ch/docs/reference/contextual/derivation.html

**Comment by adamw** [comment]
@joroKr21 actually you are right, I think @KacperFKorban fix resolves this. There is a `TypeInfo`-keyed cache in tapir's `Schema`, and as the `TypeInfo` was wrong, the cache mixed up resolved instances. There's no SOE with a snapshot version.

**Comment by kubukoz** [comment]
neat! I'll give it a try :)

**Comment by kubukoz** [comment]
hmm, I guess I can't try with the tapir Schema yet - master doesn't build due to some compilation errors https://github.com/softwaremill/tapir/runs/3817742885

**Comment by adamw** [comment]
@kubukoz Yeah, this showed up locally only after a `clean`, should be fixed now :)

**Comment by kubukoz** [comment]
Looks like it works. Can we have a release of tapir with the new magnolia? (milestone is fine of course)

**Comment by adamw** [comment]
@kubukoz done :)
