### ISSUE TITLE
Support Scala Native

### ISSUE THREAD

**Issue by propensive** [propensive/magnolia#36]
It would be nice if Magnolia worked on Scala Native. Anyone familiar with setting up Scala Native in SBT could probably tackle this.

**Comment by xuwei-k** [comment]
scala-native does not support sbt 1.x
- https://github.com/scala-native/scala-native/pull/1039
- https://github.com/propensive/magnolia/blob/eb53a6df0/project/build.properties

**Comment by propensive** [comment]
Aha, knowing that is going to same me some time, @xuwei-k -- thanks. I've been planning to build Scala Native programs directly from the command line (without SBT), but couldn't find enough documentation. Maybe I'll try a bit harder to find out, and I can do it this way.

**Comment by mielientiev** [comment]
also scala native doesn't support scala 2.12
- https://github.com/scala-native/scala-native/issues/233

**Comment by propensive** [comment]
We're still supporting 2.11.x, so at least that shouldn't be too big a problem. :)
