### ISSUE TITLE
Derivation via a chained implicit does not report errors correctly

### ISSUE THREAD

**Issue by propensive** [propensive/magnolia#44]
There are no test cases for this, but derivations which re-enter the Magnolia macro through implicit search via another implicit (e.g. `def showList[T: Show]: Show[List[T]] = ...`) do not appear to report this in the "stack trace" that's displayed when derivation fails.

**Comment by joroKr21** [comment]
Maybe `c.openImplicits` can help

**Comment by joroKr21** [comment]
Or rather this might help (don't ask why `- 2`):
```scala
val depth = c.openMacros.count(_.macroApplication.symbol == c.macroApplication.symbol) - 2
```
In general managing global state across macro invocations is brittle at best. Exploring the code I see some problems with the `recursionStack`:
* [here](https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L134-L138) frames are lost when `fn` throws an exception
* [here](https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L163-L181) `lookup` assumes that the `orElse` block doesn't modify the global `recursionStack` (thus invalidating `newStack`)
* In general, why keep a map from position to stack when it's cleared on every top-level macro invocation [here](https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L422)? This basically means there is at most one stack in this map at any given time unless aborted before reaching this point.

I would suggest a redesign of the stack to get rid of the map and have two layers instead:
1. Global layer per top-level invocation (indexed by `depth` above)
    * push / pop in `gen` (don't pop on failure)
    * always clear when `depth == 0`
2. Local layer per macro invocation
    * push / pop in `recurse` or whenever else necessary
    * clear on success in `gen` (not necessary but just in case)
    * on failure bail out without clearing to keep all frames until top-level

If we're clever we can probably combine the two layers into one by keeping some pointers.

Also caching seems orthogonal to the stack, better to have one cache per top-level call.

**Comment by propensive** [comment]
Thanks for doing this analysis! I've not been especially happy with the implementation of the mutable state in Magnolia, and its current form is very much an evolution of a variety of different experiments, while tests were being added over the course of the development. A redesign would be very welcome.

We should add a few more compile-time tests to check that the "stack trace" output works as intended.

Would you be interested in having a go at this? I can devote some time to helping this month, but while everything works "well enough", I don't have time to prioritize it myself, but any support I can give, I will!

**Comment by joroKr21** [comment]
I tried that a month ago but I couldn't make caching work. Now I just removed it and it seems fine.

**Comment by propensive** [comment]
Do you know if it has affected performance at all?

**Comment by joroKr21** [comment]
It doesn't feel like it, but if you for real performance tests we have to use JMH like in scala/compiler-benchmark

**Comment by propensive** [comment]
Did you try running the (completely undocumented) tests in the `benchmarks` directory?
