### ISSUE TITLE
magnolia scala2-v1.1.5 made generated type-classes not serializable

### ISSUE THREAD

**Issue by RustedBones** [propensive/magnolia#487]
Last release of magnolia `scala2-v1.1.5` introduced a regression, generating not serializable type-classes:

> java.io.NotSerializableException: magnolify.cats.HashDerivationSuite$PartialAssignments$macro$111$1$

See test failures in scala-steward [PR](https://github.com/spotify/magnolify/pull/823)

**Comment by adamw** [comment]
Thanks for the report - can you just double-check that 1.1.4 works fine?

**Comment by RustedBones** [comment]
We've already updated to 1.1.4 in main. The [PR](https://github.com/spotify/magnolify/pull/808) passed on the same tests.
I think this is the addition of the new object in a non serializable class that causes the issue as object outer must be serializable.

**Comment by adamw** [comment]
Releasing 1.1.6 with the problematic PR reverted
