### ISSUE TITLE
Unhelpful error for subtype with more type parameters

### ISSUE THREAD

**Issue by joroKr21** [propensive/magnolia#51]
Maybe an edge case, but not so hard to deal with. And since one of the cool features of Magnolia is the error reporting here goes:
```scala
sealed trait Politician[A]
case class Accountable[A](always: A) extends Politician[A]
case class Corrupt[A, B](appearance: A, agenda: B) extends Politician[A]
Show.gen[Politician[String]] // key not found: B
```
I see two options:
1. Existential quantification - not very useful but perfectly sound
2. Throw a more descriptive error

**Comment by propensive** [comment]
I'm not sure this is such an edge-case that we shouldn't handle it, and (2) is certainly a worst-case possibility. We could check for the existence of an upper bound on `B` (in the example above), and attempt to derive for that type.

Any thoughts?

**Comment by joroKr21** [comment]
I prefer option (1) too. Then it would be up to the user to make sure that e.g. `Typeclass[Corrupt[A, _]]` implicit is available. You are right about the upper bound (when `B` is covariant of course). In fact this is exactly what [`existentialAbstraction`](http://www.scala-lang.org/api/2.12.4/scala-reflect/scala/reflect/api/Internals$InternalApi.html#existentialAbstraction(tparams:List[Internals.this.Symbol],tpe0:Internals.this.Type):Internals.this.Type) does.

**Comment by propensive** [comment]
Yes, seems reasonable. I often forget the additional dimension existential types bring to implicit search, but I think it's the most complete solution we have.
