### ISSUE TITLE
Leaking compiler generated names

### ISSUE THREAD

**Issue by joroKr21** [propensive/magnolia#52]
We signed up for this by using macros :smile: 
```scala
println(Show.gen[List[Int]].show(List(1,2,3)))
// ::(head=1,tl$access$1=::(head=2,tl$access$1=::(head=3,tl$access$1=Nil())))
```
Same as milessabin/shapeless#768

**Comment by propensive** [comment]
Interesting... ;) Thanks for reporting this. The only alternative I can think of would be to refuse to derive cases where we can detect that the names are compiler-generated. But that seems less useful.

Any objects to me closing this issue `wontfix`, unless you can suggest an alternative?

**Comment by joroKr21** [comment]
The middle ground would be a warning. Other than that it's fine since you can call `::(1,Nil).tl$access$1` in regular Scala as well. Just something to be aware of.
