### ISSUE TITLE
Spurious error messages on successful derivation across chained implicits

### ISSUE THREAD

**Issue by propensive** [propensive/magnolia#6]
If Magnolia is called via a chained implicit, which is itself inferred by Magnolia, the nested invocation will report some errors, even if the entire derivation succeeds. The macro needs to differentiate between a nested and outer invocation, and only output errors in the latter case.

**Comment by propensive** [comment]
Need to write a test to confirm that this is no longer the case (or fix it).

**Comment by joroKr21** [comment]
Did you mean something like #60?

**Comment by joroKr21** [comment]
Stale issue, we haven't seen anything like that in a while.
