### ISSUE TITLE
Derivation breaks when type classes depend on each other

### ISSUE THREAD

**Issue by joroKr21** [propensive/magnolia#60]
Magnolia assumes the type class being derived is always the same as the root.
Say we change `Show.seq` (for demonstration's sake):
```scala
// Now we also require Default[A] - a different Magnolia-derived type class
implicit def seq[A](implicit A: Default[A], default: Default[A]): Show[String, Seq[A]] =
  // ... doesn't matter
```
Then we add another type of branch to `Tree`:
```scala
case class Many[+B](children: Tree[B]*) extends Tree[B]
```
Whoops, cache invalidation is hard:
```scala
Show.gen[Tree[String]]
// sbt:magnolia>
[error] .../magnolia/tests/src/main/scala/tests.scala:67:20: type mismatch;
[error]  found   : magnolia.examples.Show.Typeclass[magnolia.tests.Tree[String]]
[error]     (which expands to)  magnolia.examples.Show[String,magnolia.tests.Tree[String]]
[error]  required: magnolia.examples.Default[magnolia.tests.Tree[String]]
[error]   examples.Show.gen[Tree[String]]
```
Granted, the example above is contrived but situations like this can easily arise when mixing different libraries that use Magnolia for deriving type classes.

The fix would be something along the lines of using `Typeclass[T]` instead of `T` as the key everywhere.

**Comment by propensive** [comment]
Ah, well diagnosed. I've seen some evidence that the caching which causes this problem is actually not doing anything useful because the compiler does the caching *anyway*. I need to investigate further to be certain, but I've created #65 to track it.
