### ISSUE TITLE
Derivation fails with a StackOverflowError at runtime

### ISSUE THREAD

**Issue by octoro** [propensive/magnolia#66]
This fails with a StackOverflowError at runtime
```scala
  case class Recursive( r: Seq[Recursive] )
  println( magnolia.examples.Show.gen[Recursive].show( Recursive( List( Recursive( Nil) ) ) ) )
```

And surprisingly this does work, if a sealed trait is added on top of the case class.
```scala
  sealed trait Recursive2
  case class Recursive1( r: Seq[Recursive2] ) extends Recursive2
  println( magnolia.examples.Show.gen[Recursive2].show( Recursive1( List( Recursive1( Nil) ) ) ) )
```
And capturing the show instance as an implicit val produces a NullPointerException
```scala
  case class Recursive( r: Seq[Recursive] )
  implicit val showRecursive : Show[String,Recursive] = Show.gen[Recursive]
  println( showRecursive.show( Recursive( List( Recursive( Nil ) ) ) ) )
```

**Comment by joroKr21** [comment]
The SO looks easy to fix (just make parameters lazy vals and take typeclass instances byname similar to subtypes of sealed traits). The NPE however is just how implicits work in Scala:
```scala
object Foo { implicit val bar: String = implicitly[String] }
Foo.bar // null
```
Honestly, this confuses people all the time. I've never encountered a situation where you would want the implicit value available on its own RHS. But that's just an artifact of Scala's values being recursive by default. A more sensible option would be to have a special `let rec` construct, but that ship has sailed.

**Comment by octoro** [comment]
Isn't the implicit value being available on the RHS how you 'tie the knot' when deriving recursive types?

I mean how I picture the macro generated code should look like is something like:

```scala
  case class Recursive( r: Seq[Recursive] )
  implicit val showRecursive : Show[String,Recursive] = new Show[String,Recursive] { 
    def show( value: Recursive ) : String = s"Recursive(r=${Show.seq.show(value.r)})"
  } 
  println( showRecursive.show( Recursive( List( Recursive ( Nil ) ) ) ) )  
```
And this indeed does work, for any number of recursions, because the Show.seq implicitly captures the same showRecursive instance.

To me it seems that the NPE is triggered when it can't tie the knot. If i add a check to the seq method in Show:
```scala
  implicit def seq[A](implicit A: Show[String, A]): Show[String, Seq[A]] =
    new Show[String, Seq[A]] {
      def show(as: Seq[A]): String = if( A == null ) "showA was null" else as.iterator.map(A.show).mkString("[", ",", "]")
    }

```

the NPE case prints:
```
Recursive(r=showA was null)
```

**Comment by joroKr21** [comment]
No you can't tie the knot with an implicit val without [byname implicits](https://github.com/scala/scala/pull/6050) which is why this is done explicitly by the macro. What you can do though is shoot yourself in the foot :D Because usually we want available instances in scope to take precedence over derived ones, we first try to find one and indeed we do - the uninitialized enclosed implicit val. You would need special logic that hacks the compiler to handle this - see the implementation of [`cachedImplicit` in shapeless](https://github.com/milessabin/shapeless/blob/737e6e04c2974a1f71ce42cde34450ad697479be/core/src/main/scala/shapeless/package.scala#L137-L172) which does exactly that.

**Comment by octoro** [comment]
Aren't byname implicits / Lazy, etc. mainly a fix for diverging implicit expansion?

On the prioritization of implicits, if I'm not using Magnolia in full-auto mode (gen is not implicit) I think I don't need to worry about this? What triggered this problem was using Magnolia with scalaz.derive, which then produced the NPE. If I can handwrite the same kind of an instance that I'm expecting Magnolia to write, and it works, then shouldn't this be possible (the NPE case)?

I'm a bit confused about what you're saying, do you think the NPE case is a bug or user error?

**Comment by joroKr21** [comment]
Byname implicits / `Lazy` handle both divergence and tying the knot.

In general you can't say that any code that can be written by hand can also be automatically generated. In this case it is possible though, #68 fixes both the NPE and SO.

However, note that they can resurface if the typeclass implementation is not lazy enough or can't handle recursive data. This is the case with `Default` for example.
