### ISSUE TITLE
Finding typeclasses for each parameter is not always necessary

### ISSUE THREAD

**Issue by propensive** [propensive/magnolia#75]
There are cases where the construction of a typeclass corresponding to a generic type does not actually need to find a typeclass corresponding to each one of its parameters, because they're not used in the constructed value, e.g. when only the type's name is used, not its parameters.

It should be possible to construct such a typeclass without resolving unnecessary typeclasses for every parameter.

**Comment by propensive** [comment]
This functionality is probably provided through https://github.com/propensive/adversaria, so I'll close this issue.

**Comment by Odomontois** [comment]
Could you provide some example how to exclude some fields from the implicit search using annotations?

**Comment by propensive** [comment]
The "functionality" I was referring to was just for getting the names of the parameters and/or the case class name, without doing any generic derivation. That's something Adversaria does, though it doesn't really handle the more general case where, for example, only the first parameter is used.

Do you have a particular use case in mind, and I can think about how that might be solved...

**Comment by Odomontois** [comment]
Typical usage of such omission could be described in term of slightly modified `Show` derivation example:
suppose we have
```
  final case class hidden()                       extends StaticAnnotation
```
and this `combine` implementation
```scala
  def combine[T](ctx: CaseClass[Typeclass, T]): Show[T] = { value =>
    if (ctx.isValueClass) {
      val param = ctx.parameters.head
      param.typeclass.show(param.dereference(value))
    } else {
      val paramStrings = ctx.parameters.iterator.filter(param => !param.annotations.contains(hidden())).map { param =>
        val pvalue: param.PType = param.dereference(value)
        val shown               = param.typeclass.show(pvalue)
        s"${param.label}=$shown"
      }

      join(ctx.typeName.short, paramStrings)
    }
  }
```

now we already know that `Typeclass` instances for members with `hidden` annotation are not used
In shapeless I'd do thing like that with type tags and special derivation instance for tagged fields.

In Magnolia derivation currently I'm forced to require `Show` instances even for hidden fields

**Comment by propensive** [comment]
That's a good example, actually, and I think there should be a solution which uses Adversaria, where we would provide a "dummy" `Show` instance (implemented so as not to show anything) for the hidden fields which would resolve even when the appropriate `Show` typeclass doesn't exist. I will need to experiment some more with this approach, and it might require a couple of changes to Adversaria...
