### ISSUE TITLE
generated type references are not fully quality

### ISSUE THREAD

**Issue by fommil** [propensive/magnolia#77]
magnolia will not work if scalac is using `-Yno-imports` because of a use of `Any` instead of `_root_.scala.Any`

I haven't figured out where it is yet...

**Comment by fommil** [comment]
found it

https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L324

**Comment by propensive** [comment]
Fixed in 0.7.1.
