### ISSUE TITLE
[Circe] Recursive type derivation doesn't pick up default codecs

### ISSUE THREAD

**Issue by vpavkin** [propensive/magnolia#87]
Reproduction: https://github.com/vpavkin/magnolia/blob/e278256e713ddf3b1aa3365898e930eff168274b/tests/src/main/scala/CirceRecursiveTypeTest.scala

For types of this shape:

```scala
case class Recursive(field: Int, recursion: List[Recursive])
```
Problem here is that we expect the same behaviour as shapeless `Lazy` provides - the derived codec itself would be visible and used to construct the codec for `List` using circe std one.

Magnolia doesn't see it and derives coproduct codec for `List` instead, which doesn't look nice for json API:
```
  {
   "::":{
      "head":{
         "field":2,
         "recursion":{
            "Nil":"Nil"
         }
      },
      "tl$access$1":{
         "Nil":"Nil"
      }
   }
}
```

**Comment by joroKr21** [comment]
Turning on `-Xlog-implicits` shows (disregarding noise) an access error for `magnolia.Deferred`. It looks like it should be made public for the sole purpose of typechecking.

**Comment by vpavkin** [comment]
Actually I found another small problem, related to this particular testcase. Will file another issue.
