### ISSUE TITLE
http://magnolia.work is blocked by Watch Guard

### ISSUE THREAD

**Issue by pme123** [propensive/magnolia#90]
Just for your information:
![i19 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/3437927/38562107-12d08ad2-3cda-11e8-85b9-5a60305906cf.png)

This means:
"Elevated Exposure contains sites that camouflage their true nature or identity, or that include elements suggesting latent malign intent."

**Comment by pme123** [comment]
I changed the job - so I cannot test that. No problems here;).

**Comment by propensive** [comment]
Ok, I'm going to close the issue, and hopefully nobody else has the same problem. :)
