### ISSUE TITLE
lazy val leads to illegal premature access error

### ISSUE THREAD

**Issue by mrdziuban** [propensive/magnolia#95]
When taking an implicit type class instance in a class definition, the fact that magnolia produces a `lazy val` causes errors saying that "access of lazy value...would require illegal premature access to the unconstructed `this`". Here's a code example:

```scala
import magnolia.{CaseClass, Magnolia, SealedTrait}
import scala.language.experimental.macros

trait Csv[A] { def apply(a: A): List[String] }

object Csv {
  type Typeclass[A] = Csv[A]

  def combine[A](ctx: CaseClass[Csv, A]): Csv[A] = new Csv[A] {
    def apply(a: A): List[String] =
      ctx.parameters.foldLeft(List[String]())((acc, p) => acc ++ p.typeclass(p.dereference(a)))
  }

  def dispatch[A](ctx: SealedTrait[Csv, A]): Csv[A] = new Csv[A] {
    def apply(a: A): List[String] = ctx.dispatch(a)(sub => sub.typeclass(sub.cast(a)))
  }

  implicit def deriveCsv[A]: Csv[A] = macro Magnolia.gen[A]
  
  implicit val csvStr: Csv[String] = new Csv[String] { def apply(a: String): List[String] = List(a) }
}

class GenericThing[A]()(implicit ca: Csv[A])
case class Foo(s: String)
object genFoo extends GenericThing[Foo]()
/*
Implementation restriction: access of lazy value paramTypeclass$macro$3$1
in object genFoo from <$anon: Function0>, would require illegal premature
access to the unconstructed `this` of object genFoo in class Playground
*/
```

You can test this example using [this scastie](https://scastie.scala-lang.org/mrdziuban/cK0qUHILQ46dtNmVg4b2cg).

If I change [this line](https://github.com/propensive/magnolia/blob/master/core/shared/src/main/scala/magnolia.scala#L259) to just use `val` instead of `lazy val`, this example compiles, but I'm not sure what drawbacks that might have.

**Comment by joroKr21** [comment]
I guess it was made lazy to be extra sure that derivation for recursive types would work. But in its current form it wouldn't work anyway because it's missing a type annotation. Since the tests pass regardless maybe making it a (strict) val would be ok. But the other lazy val needs to remain lazy.

**Comment by mrdziuban** [comment]
Thanks for the quick response @joroKr21. Should I open a pull request with this change?

**Comment by joroKr21** [comment]
:+1: from me for a PR

**Comment by mrdziuban** [comment]
PR opened at #96.

**Comment by propensive** [comment]
Reopening while #96 is still open.

**Comment by joroKr21** [comment]
#96 is merged

**Comment by joroKr21** [comment]
This appears already fixed. Feel free to reopen if it's still an issue.
